//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Willowcat.CharacterGenerator.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Willowcat.CharacterGenerator.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible	10 50 91	05 25 86	03 15 84	02 10 83	01 05 82	01 05 82	00 00 81	00 00 81	00 -20 77
        ///NoWay   	15 75 96	10 50 91	07 35 88	05 25 86	03 15 84	02 10 83	01 05 82	01 05 82	00 00 81
        ///VeryUnlikely	16 85 97	13 65 94	10 50 91	09 45 90	05 25 86	03 15 84	02 10 83	01 05 82	01 05 82
        ///Unlikely	18 90 99	15 75 96	11 55 92	10 50 91	07 35 88	04 20 85	03 15 84	02 10 83	01 05 82
        ///EvenOdds	19 95 100	16 85 97	15 75 96	13 65 94	10 50 91	07 35 88	05 25 86	03 15 84	02 10 83
        ///SomewhatLikely	19 95 100	18 90 99	16 85 97	16 80  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MythicFateChart {
            get {
                return ResourceManager.GetString("MythicFateChart", resourceCulture);
            }
        }
    }
}
